---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.templates.app_secret .}}
type: Opaque
data:
  AMQ_USER: {{ b64enc .Values.admin.user }}
  AMQ_PASSWORD: {{ b64enc .Values.admin.password }}
  AMQ_CLUSTER_USER: {{ b64enc .Values.admin.cluster_user }}
  AMQ_CLUSTER_PASSWORD: {{ b64enc .Values.admin.cluster_password }}