{{- if .Values.security.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.templates.app_secret .}}
type: Opaque
data:
  AMQ_USER: {{ b64enc .Values.admin.user }}
  AMQ_PASSWORD: {{ b64enc .Values.admin.password }}
{{- end }}
{{- if .Values.parameters.tls_enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.templates.app_certificates . }}
type: Opaque
data:
  AMQ_KEYSTORE_PASSWORD: {{ b64enc .Values.tls.keystore_password }}
  AMQ_TRUSTSTORE_PASSWORD: {{ b64enc .Values.tls.truststore_password }}
  {{- range tuple .Values.tls.keystore .Values.tls.truststore }}
  {{ . }}: |- 
    {{ ( printf "%s%s" "tls/" . | $.Files.Get ) | b64enc }}
  {{- end }}
{{- end }}
