---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.templates.pvc_name . }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.application.volume_capacity }}