--- 
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: {{ .Values.application.name }}
  name: {{ tpl .Values.templates.route . }}-console
spec:
  to:
    kind: Service
    name: {{ tpl .Values.templates.service .}}-jolokia
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
