{{- $application_name := .Values.application.name }}
{{- $svc_name := tpl .Values.templates.service . }}
{{- $dc_name := tpl .Values.templates.deployment . }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's headless, non load balanced service
  labels:
    application: {{ $application_name }}
    app: {{ $application_name }}
  name: {{ $svc_name }}
spec:
  {{- if eq .Values.kind "StatefulSet" }}
  clusterIP: None
  {{- end }}
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  {{- range .Values.service }}
  - port: {{ .port }}
    name: {{ .name }}
    protocol: {{ .protocol }}
    targetPort: {{ .port }}
  {{- end }}
  selector:
    deployment: {{ $dc_name }}

