application:
  name: amq-broker-clustered-ssl
  amq_broker_version: 7.8
  amq_broker_image: registry.redhat.io/amq7/amq-broker
  pullPolicy: IfNotPresent
  volume_capacity: 1G
  replicas: 2
  storageclass: default

service:
  - name: jolokia
    description: "The Jolokia Management Console Service"
    protocol: TCP
    port: 8161
  - name: amqp
    description: "Plain AMQP protocol service endpoint"
    protocol: TCP
    port: 5672
  - name: mqtt
    description: "Plain MQTT protocol service endpoint"
    protocol: TCP
    port: 1883
  - name: stomp
    description: "Plain STOMP protocol service endpoint"
    protocol: TCP
    port: 61613
  - name: multiplex
    description: "Multiplexed protocol endpoint (CORE+All the others)"
    protocol: TCP
    port: 61616

ping_service:
  name: "{{ .Values.application.name }}-ping-svc"
  port: 8888

nodeport:
  port: 30002
  service: multiplex
  enabled: true

tls:
  keystore: keystore.ks
  truststore: keystore.ts
  keystore_password: kspwd
  truststore_password: tspwd

parameters:
  amq_protocols: "openwire,amq,stomp,mqtt,hornetq,core"
  amq_admin_role: "admin"
  amq_broker_name: "broker"
  amq_global_max_size: "200 mb"
  amq_require_login: False
  amq_extra_args: ""
  amq_anycast_prefix: "jmx.queue."
  amq_multicast_prefix: "jmx.topic."
  amq_enable_metrics_plugin: False
  amq_journal_type: "nio"
  amq_data_dir: "/opt/amq/data"
  amq_data_dir_logging: True
  amq_allow_anonymous: False
  amq_clustered: True
  ssl_provider: "jdk" # alternative is openssl
  amq_force_addresses_cleanup: True # if true remove all queues that are not declared here upon chart update

templates:
  service: "{{ .Values.application.name }}-svc-headless"
  service_account: "{{ .Values.application.name }}-sa"
  k8s_role: "{{ .Values.application.name }}-role"
  k8s_rolebinding: "{{ .Values.application.name }}-rolebinding"
  deployment: "{{ .Values.application.name }}-deployment"
  route: "{{ .Values.application.name }}-route"
  broker_image: "{{ .Values.application.amq_broker_image }}:{{ .Values.application.amq_broker_version }}"
  override_cm: "{{ .Values.application.name }}-override-cm"
  config_cm: "{{ .Values.application.name }}-config-cm"
  app_secret: "{{ .Values.application.name }}-secret"
  app_certificates: "{{ .Values.application.name }}-certificates"
  pvc_name: "{{ .Values.application.name}}-persistent-volume"

admin:
  user: admin
  password: password
  cluster_user: cluster_admin
  cluster_password: cluster_password
  roles: 
    - admin

users: []
#  - name: demouser
#    password: "demo"
#    roles:
#      - user
#  - name: anotheruser
#    password: "demo1"
#    roles:
#      - user
#
queues: []
#  - name: QUEUE_1
#    type: anycast # for queues, choose 'multicast' for topics
#    dlq_address: QUEUE_1_DLQ
#    expiry_address:
#    max_delivery_attempts:
#    redelivery_delay:
#    max_size_bytes:
#    message_counter_history_day_limit:
#    address_full_policy:
#    permissions:
#      - grant: consume
#        roles:
#          - admin
#          - user
#      - grant: browse
#        roles:
#          - admin
#          - user
#      - grant: send
#        roles:
#          - admin
#          - user
#      - grant: manage
#        roles:
#          - admin
#      #- grant: createNonDurableQueue # uncomment this when declaring topics (with type: multicast)
#      #  roles:
#      #    - admin
#      #    - user

# k8s resources
resources: {}
#  limits:
#    cpu: 1000m
#    memory: 2000Mi
#  requests:
#    cpu: 200m
#    memory: 1000Mi
#

