{{- if eq .Values.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: {{ .Values.application.name }}
  name: {{ tpl .Values.templates.deployment . }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      application: {{ .Values.application.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      # trigger deployments on config map changes
      annotations:
        configmap/checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        application: {{ .Values.application.name }}
        deployment: {{ tpl .Values.templates.deployment . }}
      name: {{ tpl .Values.templates.deployment . }}
    spec:
      {{- include "amq.pod" . | nindent 6 }}
      volumes:
        - name: broker-config-script-custom
          configMap:
            name: {{ tpl .Values.templates.override_cm . }}
            items:
              - key: configure_custom_config.sh
                path: configure_custom_config.sh
            defaultMode: 0550
        - name: broker-config-volume
          projected:
            sources:
            - configMap:
                name: {{ tpl .Values.templates.config_cm . }}
            {{- range .Values.security.secrets }}
            - secret:
                name: {{ . }}
            {{- end }}
        - name: {{ tpl .Values.templates.pvc_name . }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.templates.pvc_name . }}
{{- end }}