{{- if .Values.security.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.templates.app_secret .}}
type: Opaque
data:
  AMQ_USER: {{ b64enc .Values.admin.user }}
  AMQ_PASSWORD: {{ b64enc .Values.admin.password }}
{{- end }}