application:
  name: amq-broker-basic
  rolloutTrigger: ConfigChange
  amq_broker_version: 7.7
  amq_broker_image: registry.redhat.io/amq7/amq-broker
  pullPolicy: IfNotPresent
  nodePort: 30000

service:
  jolokia_port: 8161
  amqp_port: 5672
  mqtt_port: 1883
  stomp_port: 61613
  tcp_port: 61616

parameters:
  amq_protocols: "openwire,amq,stomp,mqtt,hornetq,core"
  amq_admin_role: "admin"
  amq_broker_name: "broker"
  amq_global_max_size: "100 gb"
  amq_require_login: False
  amq_extra_args: ""
  amq_anycast_prefix: "jmx.queue."
  amq_multicast_prefix: "jmx.topic."
  imagestream_namespace: "openshift"
  amq_enable_metrics_plugin: False
  amq_journal_type: "nio"

templates:
  service: "{{ .Values.application.name }}-svc"
  deployment: "{{ .Values.application.name }}-dc"
  route: "{{ .Values.application.name }}-route"
  broker_image: "{{ .Values.application.amq_broker_image }}:{{ .Values.application.amq_broker_version }}"
  override_cm: "{{ .Values.application.name }}-override-cm"
  config_cm: "{{ .Values.application.name }}-config-cm"
  app_secret: "{{ .Values.application.name }}-secret"

users:
  - name: admin
    password: "password"
    role: admin
  - name: demouser
    password: "demo"
    role: user
  - name: anotheruser
    password: "demo1"
    role: user

queues:
  - name: demoQueue
    permissions:
      - grant: consume
        roles:
          - admin
          - user
      - grant: browse
        roles:
          - admin
          - user
      - grant: send
        roles:
          - admin
          - user
      - grant: manage
        roles:
          - admin